/**
 * Recover native testnet ETH from disposable test wallets into the deployment
 * wallet. This is deliberately opt-in: without `--execute` it only reports
 * what would move, and it refuses any RPC that is not Robinhood testnet.
 *
 * Usage (PowerShell):
 *   $env:RECOVERY_KEY_FILES = 'C:\\local\\wallets.json;C:\\local\\buyers.json'
 *   npm run recover:testnet-eth
 *   npm run recover:testnet-eth -- --execute
 *
 * `RECOVERY_KEY_FILES` accepts JSON files containing private-key strings (for
 * example the disposable wallets generated by a local test harness). It never
 * prints a key. Keep both the key files and `script/.env` out of Git.
 */

import 'dotenv/config';
import { readFileSync } from 'node:fs';
import { delimiter } from 'node:path';
import { createPublicClient, createWalletClient, formatEther, http } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';

const EXPECTED_CHAIN_ID = 46_630;
const PARENT_RPC = process.env.PARENT_RPC ?? 'https://robinhood-testnet.drpc.org';
const privateKey = process.env.DEPLOYER_PRIVATE_KEY;

if (!/^0x[0-9a-fA-F]{64}$/.test(privateKey ?? '')) {
  throw new Error('DEPLOYER_PRIVATE_KEY must be a 32-byte key in script/.env or the environment.');
}

const sourceFiles = (process.env.RECOVERY_KEY_FILES ?? '')
  .split(delimiter)
  .map((file) => file.trim())
  .filter(Boolean);

if (sourceFiles.length === 0) {
  throw new Error('RECOVERY_KEY_FILES is empty. Supply one or more local JSON wallet records.');
}

const deployer = privateKeyToAccount(privateKey as `0x${string}`);
const client = createPublicClient({ transport: http(PARENT_RPC) });
const dryRun = !process.argv.includes('--execute');
const keyPattern = /^0x[0-9a-fA-F]{64}$/;

/** Collects private-key shaped strings without ever logging the source value. */
function collectKeys(value: unknown, keys: Set<`0x${string}`>): void {
  if (typeof value === 'string') {
    if (keyPattern.test(value)) keys.add(value as `0x${string}`);
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((item) => collectKeys(item, keys));
    return;
  }
  if (value && typeof value === 'object') {
    Object.values(value).forEach((item) => collectKeys(item, keys));
  }
}

const chainId = await client.getChainId();
if (chainId !== EXPECTED_CHAIN_ID) {
  throw new Error(`Refusing to sweep: RPC returned chain ${chainId}, expected ${EXPECTED_CHAIN_ID}.`);
}

const keys = new Set<`0x${string}`>();
for (const file of sourceFiles) {
  collectKeys(JSON.parse(readFileSync(file, 'utf8')) as unknown, keys);
}

const wallets = Array.from(keys, (key) => privateKeyToAccount(key))
  .filter((wallet) => wallet.address.toLowerCase() !== deployer.address.toLowerCase());
const feePerGas = (await client.getGasPrice()) * 2n;

console.log(`\n  VOIDSCAN TESTNET ETH RECOVERY${dryRun ? ' (DRY RUN)' : ''}\n`);
console.log(`  network      Robinhood Chain testnet (${chainId})`);
console.log(`  destination  ${deployer.address}`);
console.log(`  sources      ${wallets.length} disposable wallet(s) from ${sourceFiles.length} local record(s)\n`);

let recoverable = 0n;
let transferred = 0n;
let moved = 0;

for (const wallet of wallets) {
  const balance = await client.getBalance({ address: wallet.address });
  // Estimate first. Robinhood's parent fee accounting is not assumed to be
  // Ethereum's fixed 21,000-gas transfer cost.
  const gas = ((await client.estimateGas({ account: wallet.address, to: deployer.address, value: 1n })) * 12n) / 10n;
  const reserve = gas * feePerGas;
  if (balance <= reserve) {
    console.log(`  skip  ${wallet.address}  ${formatEther(balance)} ETH (below transfer cost)`);
    continue;
  }

  const value = balance - reserve;
  recoverable += value;
  if (dryRun) {
    console.log(`  would ${wallet.address}  ${formatEther(value)} ETH`);
    continue;
  }

  try {
    const hash = await createWalletClient({ account: wallet, transport: http(PARENT_RPC) }).sendTransaction({
      account: wallet,
      chain: null,
      to: deployer.address,
      value,
      gas,
      maxFeePerGas: feePerGas,
      maxPriorityFeePerGas: 0n,
    });
    const receipt = await client.waitForTransactionReceipt({ hash });
    if (receipt.status !== 'success') throw new Error('transfer reverted');
    transferred += value;
    moved++;
    console.log(`  moved ${wallet.address}  ${formatEther(value)} ETH  ${hash}`);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    console.log(`  failed ${wallet.address}  ${reason.slice(0, 120)}`);
  }
}

console.log(`\n  ${dryRun ? 'recoverable' : 'recovered'}  ${formatEther(dryRun ? recoverable : transferred)} ETH`);
if (dryRun) console.log('  No transfer was sent. Re-run with --execute only after reviewing this list.');
else console.log(`  moved        ${moved} wallet(s)`);
