import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { parseAbi, encodeFunctionData, decodeFunctionData } from 'viem';
import { BodyError, readJsonObject } from '../web/lib/request-body';
import { MANIFEST_HASH, CONTRACTS } from '../web/lib/public-release';
import { canonicalProfile } from '../web/lib/profile-signature';

assert.equal(MANIFEST_HASH.length, 66);
assert.equal(CONTRACTS['ETH mint'].toLowerCase(), '0x4eaa37e811af0dd2405447e64065f57e0b4dd08b');
const route = readFileSync('../web/app/api/market/sponsor/route.ts', 'utf8');
assert(route.includes('function sellWithPermit(uint256,uint256,bytes)'));
assert(!route.includes('function sellWithPermit(uint256,uint256,uint8,bytes32,bytes32)'));
const abi = parseAbi(['function sellWithPermit(uint256,uint256,bytes)']);
const data = encodeFunctionData({ abi, functionName: 'sellWithPermit', args: [1n, 999n, '0x1234'] });
assert.equal(decodeFunctionData({ abi, data }).functionName, 'sellWithPermit');
assert.deepEqual(await readJsonObject(new Request('http://fixture', { method: 'POST', body: '{"ok":true}' }), 100), {ok:true});
for (const body of ['null', '[]', '"text"']) await assert.rejects(readJsonObject(new Request('http://fixture', {method:'POST',body}),100), BodyError);
let cancelled = false;
const stream = new ReadableStream<Uint8Array>({ pull(controller) { controller.enqueue(new Uint8Array(64)); }, cancel() { cancelled = true; } });
await assert.rejects(readJsonObject(new Request('http://fixture', {method:'POST',body:stream,duplex:'half'} as RequestInit),100), (error: unknown) => error instanceof BodyError && error.status === 413);
assert(cancelled, 'Oversized stream must be stopped, not buffered in full');
assert.deepEqual(canonicalProfile({socials:[null, {platform:123}] } as never).socials, []);
console.log('PASS: manifest identity, NFT sale ABI, bounded streamed JSON and malformed profile fields.');
