/** Submit the exact V11 compiler input to Blockscout and verify live bytecode. */
import { readFileSync } from 'node:fs';
import { createPublicClient, http, parseAbi, type Address } from 'viem';
import solc from 'solc';

const deployment = JSON.parse(readFileSync(process.env.V11_RECORD_FILE ?? 'deployments/testnet-v11-pending.json', 'utf8'));
const sourceCode = readFileSync('../out/standard-input.json', 'utf8');
const explorer = 'https://explorer.testnet.chain.robinhood.com';
const rpc = createPublicClient({ transport: http(deployment.network.rpc) });
const compiled = JSON.parse(solc.compile(sourceCode, {
  import: (path: string) => ({ error: `Unexpected compiler import: ${path}` }),
}));
const contracts: Record<string, string> = {
  protocolTimelock: 'contracts/parent/VoidProtocolTimelock.sol:VoidProtocolTimelock',
  escrow: 'contracts/genesis/VoidGenesisEscrowV11.sol:VoidGenesisEscrowV11',
  token: 'contracts/genesis/VoidTokenV11.sol:VoidTokenV11',
  deed: 'contracts/parent/VoidChainDeed.sol:VoidChainDeed',
  builderVault: 'contracts/genesis/VoidTimelockVaultV6.sol:VoidTimelockVaultV6',
  emissionVault: 'contracts/genesis/VoidEmissionVaultV11.sol:VoidEmissionVaultV11',
  lpLock: 'contracts/genesis/VoidPermanentLpLockV6.sol:VoidPermanentLpLockV6',
  ethPool: 'contracts/genesis/VoidEthPoolV6.sol:VoidEthPoolV6',
  ethUsdFeed: 'contracts/genesis/VoidFixedEthUsdFeedV6.sol:VoidFixedEthUsdFeedV6',
  twap: 'contracts/genesis/VoidTwapOracleV6.sol:VoidTwapOracleV6',
  oracle: 'contracts/genesis/VoidTwapFreshnessGuardV6.sol:VoidTwapFreshnessGuardV6',
  treasury: 'contracts/parent/VoidChainTreasury.sol:VoidChainTreasury',
  runtime: 'contracts/parent/VoidChainAppRuntimeV11.sol:VoidChainAppRuntimeV11',
  paymaster: 'contracts/parent/VoidPaymaster.sol:VoidPaymaster',
  appFactory: 'contracts/parent/VoidChainAppFactoryV3.sol:VoidChainAppFactoryV3',
  l3Registry: 'contracts/parent/VoidL3MigrationRegistry.sol:VoidL3MigrationRegistry',
  revenueClaimer: 'contracts/parent/VoidRevenueClaimerV11.sol:VoidRevenueClaimerV11',
  governanceVotes: 'contracts/parent/VoidGovernanceVotesV11.sol:VoidGovernanceVotesV11',
  daoFactory: 'contracts/parent/VoidChainDaoFactory.sol:VoidChainDaoFactory',
  nftImplementation: 'contracts/genesis/VoidGenesisNftAmmV6.sol:VoidGenesisNftAmmV6',
  stakingImplementation: 'contracts/genesis/VoidSoftStakingV9.sol:VoidSoftStakingV9',
  mint: 'contracts/genesis/VoidEthGenesisMintV11.sol:VoidEthGenesisMintV11',
};

async function addressRecord(address: string) {
  const response = await fetch(`${explorer}/api/v2/addresses/${address}`);
  if (!response.ok) throw Error(`Explorer read failed for ${address}: ${response.status}`);
  return response.json() as Promise<{ is_verified?: boolean; implementations?: Array<{ address_hash: string }> }>;
}
async function submit(label: string, address: string, contractName: string, constructorArgs?: string) {
  if ((await addressRecord(address)).is_verified) return null;
  const body = new URLSearchParams({
    module: 'contract', action: 'verifysourcecode', codeformat: 'solidity-standard-json-input',
    contractaddress: address, contractname: contractName,
    compilerversion: 'v0.8.28+commit.7893614a', sourceCode,
  });
  if (constructorArgs !== undefined) body.set('constructorArguements', constructorArgs);
  const response = await fetch(`${explorer}/api`, { method: 'POST', body });
  const result = await response.json() as { status?: string; result?: string };
  if (/already verified/i.test(result.result ?? '')) return null;
  if (!response.ok || result.status !== '1' || !result.result) {
    throw Error(`Verification rejected for ${label} ${address}: ${JSON.stringify(result)}`);
  }
  return result.result;
}
async function status(guid: string) {
  const response = await fetch(`${explorer}/api?module=contract&action=checkverifystatus&guid=${encodeURIComponent(guid)}`);
  return ((await response.json()) as { result?: string }).result ?? 'Unknown verification result';
}
async function verifyDeployed(label: string, address: string, contractName: string) {
  // A resumed deployment may span a Foundry test run. Foundry and the compact
  // solc builder emit identical runtime logic but different metadata hashes.
  // Once Blockscout has verified the exact address from source, do not reject
  // that address merely because the local build directory was regenerated by
  // the other compiler frontend between phases.
  if ((await addressRecord(address)).is_verified) {
    console.log(`verified ${label}`);
    return;
  }
  const deployHash = deployment.steps[`deploy:${label}`];
  if (!deployHash) throw Error(`Missing deployment transaction for ${label}`);
  const transaction = await rpc.getTransaction({ hash: deployHash });
  const [source, name] = contractName.split(':');
  const creationCode = compiled.contracts[source][name].evm.bytecode.object as string;
  const input = transaction.input.slice(2);
  if (!input.startsWith(creationCode)) throw Error(`Creation bytecode mismatch for ${label}`);
  const guid = await submit(label, address, contractName, input.slice(creationCode.length));
  if (!guid) return console.log(`verified ${label}`);
  for (let attempt = 0; attempt < 40; attempt += 1) {
    await new Promise((resolve) => setTimeout(resolve, 3_000));
    if ((await addressRecord(address)).is_verified) return console.log(`verified ${label}`);
    const result = await status(guid);
    if (/fail|unable|error/i.test(result)) throw Error(`Verification failed for ${label}: ${result}`);
  }
  throw Error(`Verification timed out for ${label}`);
}

if (await rpc.getChainId() !== 46_630) throw Error('Robinhood testnet only');
for (const [label, contractName] of Object.entries(contracts)) {
  const address = deployment.contracts[label];
  if (!address) throw Error(`Missing ${label}`);
  await verifyDeployed(label, address, contractName);
}

const gatewayAbi = parseAbi(['function implementation() view returns(address)']);
for (const label of ['softStaking', 'nftAmm']) {
  const gateway = deployment.contracts[label] as Address;
  const implementation = await rpc.readContract({ address: gateway, abi: gatewayAbi, functionName: 'implementation' });
  if ((await rpc.getCode({ address: implementation })) === '0x') throw Error(`${label} implementation has no bytecode`);
  console.log(`inspected ${label} gateway -> ${implementation}`);
}
const daoImplementation = await rpc.readContract({
  address: deployment.contracts.daoFactory, abi: parseAbi(['function implementation() view returns(address)']), functionName: 'implementation',
});
const daoContract = 'contracts/parent/VoidChainDao.sol:VoidChainDao';
const daoGuid = await submit('DAO implementation', daoImplementation, daoContract, '');
if (daoGuid) {
  for (let attempt = 0; attempt < 40 && !(await addressRecord(daoImplementation)).is_verified; attempt += 1) {
    await new Promise((resolve) => setTimeout(resolve, 3_000));
    const result = await status(daoGuid);
    if (/fail|unable|error/i.test(result)) throw Error(`DAO implementation verification failed: ${result}`);
  }
}
if (!(await addressRecord(daoImplementation)).is_verified) throw Error('DAO implementation verification timed out');
console.log(`PASS: ${Object.keys(contracts).length} V11 core contracts verified; gateways and DAO implementation inspected.`);
